### ISSUE TITLE
Spec @mentions

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1067]
Documentation: https://docs.google.com/document/d/1oRhw3DJhbVAKkHAEgyt6ccV82wtXR_11qY7JqMcesUU/edit
Author: @lukebarnard1 
Date: 14/07/2017

I.e. spell out that hyperlinking to a matrix.to URL in an HTML is a namespacing operation to generate an @mention pill

**Comment by non-Jedi** [comment]
Where is the google-doc for commenting on this? I don't understand how the mention pills relate to the spec.

**Comment by jevolk** [comment]
https://docs.google.com/document/d/1oRhw3DJhbVAKkHAEgyt6ccV82wtXR_11qY7JqMcesUU/?usp=sharing

**Comment by ara4n** [comment]
@non-Jedi - I think you are misunderstanding how matrix.to is being used here.  It is very much as an namespace (like an xmlns), so that clients which are aware of it can treat it like a URI scheme.  Clients which are *not* aware of it will treat it like a dumb URI and fall through to the matrix.to webapp itself (which is provided by matrix.org for the benefit of the whole Matrix ecosystem) but it **does not form a hard dependency on the matrix.to service whatsoever. it is just an arbitrary opaque namespace, similar to matrix:// or mx:// URLs or whatever, but one which happens for convenience to fall through to a real endpoint for stupid clients or users.**.

**Comment by non-Jedi** [comment]
@ara4n I did understand; I just disagree with the decision, and I hope it
hasn't been made yet so that I might convince you of my point of view.

My contention is that no part of a protocol that's intentionally federated
should be linked to any singleton that can be controlled. While I realize
that it is being used as a namespace primarily, in its plain reading, a
matrix.to URL is a URL, and you admit that the reason matrix.to was chosen
was so that it could be used as a URL by "dumb" clients. While the URL is
controlled by an entity that I trust right now, there is no guarantee that
it will continue to be so in the future. Tbh, I'm not all that concerned
about an attacker controlling matrix.to; I'm concerned about matrix
maintaining the principle of federation: there are no privileged servers.
While matrix.to is not a *matrix* server, if it's included in the spec, it
will still be a privileged server.

I am completely fine with matrix.to being used as a de-facto namespace. I
strongly disagree with such behavior being part of the spec.

**Comment by non-Jedi** [comment]
Thanks @jevolk. I had seen that doc before but somehow assumed it was a Riot design doc rather than a spec proposal.
