### ISSUE TITLE
Megolm session export format

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix-doc#1211]
Documentation: https://docs.google.com/document/d/1UjWpNMfof3ynFbEOtHWGmqxy_WrFZEojrGWUq_os0G8/edit
Author: @richvdh 
Date: 03/01/2017

**Comment by mujx** [comment]
Links with libraries that support the mentioned APIs & a reference implementation will be useful. The decryption part is also missing.

**Comment by ara4n** [comment]
The reference implementation is https://github.com/matrix-org/matrix-react-sdk/blob/master/src/utils/MegolmExportEncryption.js.

If there are other specific bits which feel missing when reading the google doc, please please say what they are - because if I were turning the doc into a spec PR right now, i suspect i'd copy it over verbatim and propagate whatever ambiguities are causing problems.
