### ISSUE TITLE
put something massive in proposals.rst to warn randoms not to resolve comments

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1266]

**Comment by turt2live** [comment]
Rationale: Google docs doesn't have a setting to disable the 'resolve' button on comment threads. This means that anonymous users can resolve a thread.

Google's answer to the problem is to submit feedback via Help -> Report a problem on the doc ([source](https://productforums.google.com/forum/#!topic/docs/EaBtYm-C31I))

**Comment by turt2live** [comment]
I don't think we have this problem anymore now that randoms can't resolve threads (we switched to Github).
