### ISSUE TITLE
Decentralized conversation logs

### ISSUE THREAD

**Issue by homebeach** [matrix-org/matrix-doc#1347]
When room is established, there could be option to make clients to store the logs instead of server. If some user is missing pieces of logs it would be queried from other users. As far as I know, Skype handles logging like this.

**Comment by Half-Shot** [comment]
While I understand the idea, Matrix is fundamentally server to server federation rather than true peer to peer to sidestep some of the issues such technologies have. One problem is history storage in that you are now trusting other client's to give you a better representation of the history of your room over your own client. 

Fundamentally you are expecting to trust the server you are connected to is sending you correct history (modulo event content, which a seperate issue handled by e2e) and up to date history. If a client is missing 'logs', it asks the server it is connected to for history of the room. For all intents and purposes for rooms, the client and the server act as one and any missing information is synced between server to server, and client to server. 

Syncing history from client to server not only defeats the point of Matrix.

As an aside, while I remember that skype locally stored history in the client as a optimisation (like Riot does), it categorically would never allow for history to be shared between clients and would open up numerous security holes. 

Sorry, but I think this is something that the protocol probably won't and shouldn't support.

**Comment by turt2live** [comment]
As @Half-Shot has said, matrix is fundamentally server-to-server to ensure consistency. There is a suggestion to have peer-to-peer capabilities (#710), and that might be better suited for this kind of request. By nature, p2p would mean that your client (which doubles as a server) would have the logs.

**Comment by homebeach** [comment]
Ok this seems not be be very good idea so I close this,
