### ISSUE TITLE
Does appservice timestamp massaging also apply to /kick, /ban, etc?

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1394]
The spec says "only when sending events", however there's quite a few routes that send events. Should probably explicitly declare which routes this applies to.

**Comment by turt2live** [comment]
also EDUs: can appservices send presence from the past?

**Comment by turt2live** [comment]
Looks like this currently only works for the plain `/send` event path. State events cannot be massaged, which might be a good thing?

**Comment by Half-Shot** [comment]
Currently [HEAD](https://matrix.org/docs/spec/application_service/unstable.html#client-server-api-extensions) says:

> This will only apply when sending events.

Which is a little too sneakly. I'd prefer to say explicitly only ``/send`` supports this.

Aside from that, I'd like to make it clear that this doesn't insert things into the dag through some magic ts resolving thing so you may not see events appear in the right place just because you timestamped them.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/matrix-doc/issues/1585

The tldr is that "yes, timestamp massaging should apply to everything".
