### ISSUE TITLE
Spec M_RESOURCE_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by dbkr** [matrix-org/matrix-doc#1470]
On /login and /sync

**Comment by richvdh** [comment]
is there a proposal doc for this?

**Comment by turt2live** [comment]
This error code doesn't exist anywhere. Closing.

**Comment by richvdh** [comment]
It got relplaced by M_RESOURCE_LIMIT_EXCEEDED afaict

**Comment by turt2live** [comment]
That's https://github.com/matrix-org/matrix-doc/issues/1504

**Comment by turt2live** [comment]
... except the proposal now says "this doesn't handle error codes"... reopening for tracking, and counting this as a spec-omission due to the age it has been around for. As far as I can tell, this error code was never discussed in the spec landscape, but is throughout the Synapse and react-sdk implementations of MAU limiting.

**Comment by turt2live** [comment]
***sigh*** sorry for the noise, I confused 1504 with https://github.com/matrix-org/matrix-doc/issues/1452 because of the name. This has been merged via https://github.com/matrix-org/matrix-doc/pull/1874.

Hopefully that keeps this issue closed forever.
