### ISSUE TITLE
Grammar for IS session IDs/tokens

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1611]
Sydent uses a different session token depending on the medium: https://github.com/matrix-org/sydent/blob/master/sydent/util/tokenutils.py#L20-L24

For email addresses: `[0-9a-zA-Z]{32}`
For phone numbers: `[0-9]{6}`

**Comment by turt2live** [comment]
Also note that the public API calls them "session IDs" or "sid"s, however internally to sydent they are generally called "tokens" where the "sid" represents the internal row ID for referencing the token.

**Comment by richvdh** [comment]
1. is sydent's session ID ever exposed over the API? I can't see it anywhere in the spec, but perhaps I'm missing something.

2. I assume there's a reason that the token for phone numbers is much much simpler than the one for emails, and I assume that reason is because the user is going to have to type it in. I'm therefore not sure we should be limiting this to ascii in the same way as we do with most other tokens. Do we actually need a grammar here at all, other than to say it's unicode and everyone has to pass it through correctly?

**Comment by richvdh** [comment]
> Do we actually need a grammar here at all, other than to say it's unicode and everyone has to pass it through correctly?

oh, we might need length limits, I guess.

**Comment by turt2live** [comment]
Sydent's session ID shows up as `sid` in the response of this: https://matrix.org/docs/spec/identity_service/unstable.html#post-matrix-identity-api-v1-validate-email-requesttoken (and similar APIs)

The phone number one is simpler for a couple reasons: having the user remember a 16 character string that got texted to them is not going to be fun, and might push the message limits a bit. Emails are a bit easier because they can be hidden with a "click here" link (put in the query string, or whatever).

We might not need a formal grammar like the others and can probably get away with saying "must be unicode and less than 32 characters" inline to the response spec.
