### ISSUE TITLE
Spec /keys/upload/:deviceId

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1667]

**Comment by richvdh** [comment]
I think this is just a special-case of https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-keys-upload, combined with the fact that synapse used to require (and now tolerates, for backwards compat), the device ID in the URI.

**Comment by turt2live** [comment]
turns out we're missing the `/:deviceId` route, and does indeed look like the guest version is just a special ID. I still think we should add this to the spec as an omission given the heavy usage of it.

**Comment by ahmedcharles** [comment]
Riot sends `/keys/upload/<device_id>` and the spec says `/keys/upload`, which precludes matching what Riot sends. This is made more complicated by the spec allowing multiple device ids being specified in the json body, even though that doesn't really make sense.

**Comment by richvdh** [comment]
Can we just change riot to match the spec please? As @ahmedcharles implies, the device id is in the body so there's no need for it to be repeated in the URL (and allowing it to be there opens questions we don't need to answer like "what happens when the ID in the path doesn't match the one in the body")

**Comment by turt2live** [comment]
yea, let's close this as a client bug
