### ISSUE TITLE
Put a big red box somewhere that says floats are banned

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1727]
and explain the rationale why for bonus points

**Comment by Half-Shot** [comment]
This is about power levels in particular, because it's confusing people as to why we limit ourselves to integers.

**Comment by richvdh** [comment]
https://matrix.org/docs/spec/appendices.html#canonical-json says: "Numbers in the JSON must be integers ..."

I guess it's not an obvious corollary that that extends to event contents.

**Comment by jevolk** [comment]
The extensibility of message contents in Matrix are one of its prized assets sought by prospective adopters. A diverse and innumerable amount of data encountered in everyday life leverage floating points because they represent continuous, rather than discrete quantities. Without them you will struggle to represent the majority of datasets used in finance and business; most of the sciences, even your local weather report stored and conveyed by a channel bot:

```
<jzk> !weather barometer

----------------------
| inHg  :     29.92  |
| hPa   :   1013.25  |
----------------------
```

Matrix rooms won't be capable of this. They won't be capable of storing data that bots produce and consume and communicate for humans; they won't be useful for distributed sensor networks; they won't be used as the dominate general communication protocol for the internet: something else will be instead which can. This decision narrows Matrix's usefulness and makes it more irrelevant than it was previously.


### Why?

Why? Only server implementations are burdened with the effort to maintain this compatibility and not break when parsing floats out of JSON; then be capable of printing them exactly as they were parsed to maintain the canonical signatures. There are a very small number of server implementations. In fact, there is only _one_ right now. Nevertheless even ideally, there will _always_ be a smaller number of server implementations which can be burdened to cooperate and get this aspect correct. The large and diverse number of client implementations are irrelevant here: virtually all of their JSON implementations gracefully degrade in this regard; otherwise additional gimmicks can be negotiated somewhere in c2s.

This issue speaks ignorance to me. The IEEE 754 floating point standard was laid down to address and preempt _exactly_ what you guys are doing here: washing your hands of them altogether. As stewards of the lower-level aspects of this protocol, it's easy to miss forest for the trees as your decisions emerge. This is the lazy and ignorant way out of a modest challenge.

**Comment by aaronraimist** [comment]
Sorry the title isn’t very clear, this issue is only about power levels being integers

**Comment by NotAFile** [comment]
It seems to me like a the only true solution for all of these issues is to not sign a string serialization but a binary representation of the float, which of course would be very invasive. Converting Floating point numbers to strings is nontrivial and not standardized (and there's a large number of algorithms), so I don't think this problem can ever truly be solved without changing the event signing. Unless you want to end up with a "convert_float_to_int_the_way_python_2_7_5_did_back_when_synapse_was_originally_written" function in every matrix homeserver in the future. Just banning floats is certainly a shitty way to solve this but it's only shitty because float formatting is deceptively difficult.

To demonstrate the point, here's some different languages as of november 2018 (these will probably also differ by platform, your stdlib, etc):

```
ruby -e 'puts 1.234567890 / 0.987654321'
1.249999988609375
python -c 'print 1.234567890 / 0.987654321'
1.24999998861
php -r 'echo 1.234567890 / 0.987654321;'                                                                                                                                            
1.2499999886094
perl -e "print 1.234567890 / 0.987654321;"
1.24999998860938
perl6 -e "print 1.234567890 / 0.987654321;"
1.2499999886
node -e "console.log(1.234567890 / 0.987654321)"
1.249999988609375
java:
1.249999988609375
rust:
1.249999988609375
```

Okay, so at least java, rust, node, python3 and ruby are the same. Until...

```
ruby -e 'puts 1000000000000000.0'
1.0e+15
python3 -c 'print(1000000000000000.0)'                                                                                                                                                 
1000000000000000.0
python3 -c 'print( 10000000000000000.0)' # one zero more than ruby required
1e+16
python -c 'print( 100000000000.0)' # python2 starts it at 1e+11
1e+11
java: (from 1.0E7 and up)
1.0E15
...
```

**Comment by jevolk** [comment]
Just perusing through [wikipedia](https://en.wikipedia.org/wiki/Venus):

> Venus is the second planet from the Sun, orbiting it every 224.7 Earth days.[13] ...  It is the second-brightest natural object in the night sky after the Moon, reaching an apparent **magnitude** of −4.6 – bright enough to cast shadows at night and, rarely, visible to the naked eye in broad daylight.[15][16] ... its maximum angular distance from the Sun (elongation) is 47.8°.

> The diameter of Venus is 12,103.6 km (7,520.8 mi)—only 638.4 km (396.7 mi) less than Earth's—and its mass is 81.5% of Earth's. Conditions on the Venusian surface differ radically from those on Earth because its dense atmosphere is 96.5% carbon dioxide, with most of the remaining 3.5% being nitrogen.[23]

Congratulations. By unilaterally making this decision you have massively *devalued* the richness of the Matrix system, or at least your server. [Construct](https://github.com/matrix-construct/construct) will be adhering to the IEEE 754 floating point standard and will be capable of parsing and printing floating points which will best-effort to not break signatures. Thus [Construct](https://github.com/matrix-construct/construct) a more valuable and versatile option to choose due to the fact that supporting floating points according to the IEEE 754 standard makes it _more robust by supersetting_ your implementation's capabilities. I guess this debate will now be a matter for the soft-failure mechanisms.

> Sorry the title isn’t very clear, this issue is only about power levels being integers

@aaronraimist I empathize with your dismay. Further, I pity and share your confusion. It makes complete and total sense to specify that power levels should be integers. It's a real whopper to take it further and eliminate floating points altogether from an extensible JSON system. It would be better if this area of the specification was delegated to qualified computer scientists who studied floating point applications and their limitations rather than the current parvenu decision process.

**Comment by jevolk** [comment]
> To demonstrate the point, here's some different languages as of november 2018 (these will probably also differ by platform, your stdlib, etc):
> 
> ```
> ruby -e 'puts 1.234567890 / 0.987654321'
> 1.249999988609375
> python -c 'print 1.234567890 / 0.987654321'
> 1.24999998861
> php -r 'echo 1.234567890 / 0.987654321;'                                                                                                                                            
> 1.2499999886094
> perl -e "print 1.234567890 / 0.987654321;"
> 1.24999998860938
> perl6 -e "print 1.234567890 / 0.987654321;"
> 1.2499999886
> node -e "console.log(1.234567890 / 0.987654321)"
> 1.249999988609375
> java:
> 1.249999988609375
> rust:
> 1.249999988609375
> ```

JSON doesn't conduct floating point operations, it just represents floating point integer data. So I'm struggling to find how these examples are relevant.


> Okay, so at least java, rust, node, python3 and ruby are the same. Until...
> 
> ```
> ruby -e 'puts 1000000000000000.0'
> 1.0e+15
> python3 -c 'print(1000000000000000.0)'                                                                                                                                                 
> 1000000000000000.0
> python3 -c 'print( 10000000000000000.0)' # one zero more than ruby required
> 1e+16
> python -c 'print( 100000000000.0)' # python2 starts it at 1e+11
> 1e+11
> java: (from 1.0E7 and up)
> 1.0E15
> ...

It would be better to show JSON output from these inputs in these languages. I'm actually curious to know. Thanks.

**Comment by NotAFile** [comment]
>JSON doesn't conduct floating point operations, it just represents floating point integer data. So I'm struggling to find how these examples are relevant.

The math operations were just ways to generate an arbitrary float without directly entering it as a string to now show artifacts of the dec float->bin float conversion. But you are right that 

> It would be better to show JSON output from these inputs in these languages. I'm actually curious to know. Thanks.

These differences do apply to JSON encoding, as any language will very likely use the same float->str operation for both. it would have been better if I'd shown json, but it would also have taken a lot longer to look it up.

I did check it though, here's node/v8 and python, as you can tell they differ:

```
python3 -c 'import json;print(json.dumps({"a": 10000000000000000.0}))'
{"a": 1e+16}
node -e 'console.log(JSON.stringify({"a": 1000000000000000000000.0}))'
{"a":1e+21}
```

**Comment by jevolk** [comment]
> ```
> python3 -c 'import json;print(json.dumps({"a": 10000000000000000.0}))'
> {"a": 1e+16}
> node -e 'console.log(JSON.stringify({"a": 1000000000000000000000.0}))'
> {"a":1e+21}
> ```

Those look the same to me. It also might help if `10000000000000000.0` was the same as `1000000000000000000000.0` for a more controlled experiment.

**Comment by NotAFile** [comment]
> Those look the same to me. It also might help if `10000000000000000.0` was the same as `1000000000000000000000.0` for a more controlled experiment.

These are deliberately not the same. These are both at the minimum required to switch to e notation.

Maybe showing the same number does make it clearer:

python3 -c 'import json;print(json.dumps({"a": 100000000000000000000.0}))'
{"a": 1e+20}
node -e 'console.log(JSON.stringify({"a": 100000000000000000000.0}))'
{"a":100000000000000000000}

**Comment by jevolk** [comment]
> Maybe showing the same number does make it clearer:
> 
> ```
> python3 -c 'import json;print(json.dumps({"a": 100000000000000000000.0}))'
> {"a": 1e+20}
> node -e 'console.log(JSON.stringify({"a": 100000000000000000000.0}))'
> {"a":100000000000000000000}
> ```

The way my JSON implementation handles this is by verifying the JSON text as close to as it arrives on the wire (in this case removing the spaces). That's the robust basis for [Construct](https://github.com/matrix-construct/construct)'s continued support for floats if they come down the wire. The specification should start here to figure out how to synthesize these differences for inferior *canonical JSON* implementations. The specifiers should contemplate:
- Can floating point outputs be tweaked to conform to a canonical output among several *canonical-capable JSON* implementations.
- Can the same (or a small number) of *canonical-capable JSON* implementations with a conforming floating point output be ported to enough platforms and languages.

Consider that *canonical* JSON is already a limitation for implementations and languages. For example the python3 `json.dumps()` as it appears there is not canonical because it has spaces so that won't even be viable for signing. The specifiers should remember this existing limitation: you can't just use any old default JSON implementation in any old language to speak to the federation *as is*. That limitation is an advantage here and perhaps the useful starting point to specify a realistic set of rules for floats.

**Comment by jevolk** [comment]
> signing and verifying blocks of JSON text as text

I'd just like to reemphasize this point. You guys have created this problem for yourself and now you're paying a price by universally eliminating floats for the entire matrix system. You've voluntarily chosen to degrade the value of your own system for literally no substantive reason at all. **Once again you created your own problem** which didn't need to exist nor needs to continue to exist. Frankly, ignore my bullet points in the prior message, I'm wrong there.

> All languages and libraries can conduct network operations with strings of text; do that. FFS.

The right solution here is to fix fundamental notions of what canonical JSON is -- rethink that. Then you won't find yourself back here with this issue or countless others that emerge from it.

**Comment by jevolk** [comment]
@NotAFile Doesn't your example extend to integers as well as floats here? Are floats specifically relevant to illustrate that divergence?

```
$ nodejs -e 'console.log(JSON.stringify({"a": 100000000000000000000.0}))'
{"a":100000000000000000000}
$ nodejs -e 'console.log(JSON.stringify({"a": 100000000000000000000}))'
{"a":100000000000000000000}
$ python3 -c 'import json;print(json.dumps({"a": 100000000000000000000.0}))'
{"a": 1e+20}
$ python3 -c 'import json;print(json.dumps({"a": 100000000000000000000}))'
{"a": 100000000000000000000}
$ python3 -c 'import json;print(json.dumps({"a": 1e+20}))'
{"a": 1e+20}
$ nodejs -e 'console.log(JSON.stringify({"a": 1e+20}))'
{"a":100000000000000000000}
$ python3 -c 'import json;print(json.dumps({"a": 100000000000000000000.0}))'
{"a": 1e+20}
$ python3 -c 'import json;print(json.dumps({"a": 100000000000000000000.1}))'
{"a": 1e+20}
```
So, about canonical JSON...

**Comment by jevolk** [comment]
Also, [RFC7159 allows for exponents](https://tools.ietf.org/html/rfc7159#section-6) while New Vector's [Canonical JSON](https://matrix.org/docs/spec/appendices.html#grammar) grammar does not.

@turt2live Please update the title to include exponent notation along with floats so it doesn't get forgotten in the big red box too, thanks.

**Comment by NotAFile** [comment]
Exponent notation implies floats... in most languages anyway. All languages I've checked will not use exponent notation in JSON if you pass them integers, thus not causing any of the formatting issues. This is why I added a .0 to the end of my examples. If you remove that, Python will just insert the number as text like expected. Node is special here, because it does not have integers, only floats. So it will always use exponent notation.

**Comment by jevolk** [comment]
@NotAFile First of all it just adds a slight amount confusion to have your examples out of range for [Canonical JSON](https://matrix.org/docs/spec/appendices.html#canonical-json).
> Numbers in the JSON must be integers in the range `[-(2**53)+1, (2**53)-1].`

```
>>> canonical = pow(2, 53) - 1
>>> notafile = 100000000000000000000
>>> notafile <= canonical
False
```
Nevertheless I think I see the point you're trying to illustrate with them. So consider the following:
```
$ nodejs
> JSON.stringify(JSON.parse("{\"a\":1e+20}"));
'{"a":100000000000000000000}'
> JSON.stringify(JSON.parse("{\"a\":100000000000000000000}"));
'{"a":100000000000000000000}'
```
What you're looking at there is a unate conversion to integer notation; now consider:
```
> JSON.stringify(JSON.parse("{\"a\":1e+21}"));
'{"a":1e+21}'
> JSON.stringify(JSON.parse("{\"a\":1000000000000000000000}"));
'{"a":1e+21}'
```
In contrast, this is a unate conversion to exponent notation. This is a problem. One will not achieve Canonical JSON with this implementation given these inputs because the outputs have to be the same. These properties make the hash used for the ed25519 signatures match and what Canonical JSON is all about.

Finally, reconsider Canonical JSON after the #1013 shit-show where there is actually a way to deal with this: relaxation of this input/output reflection which allows for said inputs to be different if they produce the desired output. This means that exponent notation has to be converted to integer notation. Considering #1013 I guess that's okay. It still seems silly for all the reasons #1013 is silly.

Anyway back on topic, **what I still don't grok about this issue is why a float cannot achieve the required needs of Canonical JSON.**

```
$nodejs
> JSON.stringify(JSON.parse("{\"a\":1000000000000000.1}"));
'{"a":1000000000000000.1}'
```
```
$python3
>>> json.dumps(json.loads('{"a":1000000000000000.1}'))
'{"a": 1000000000000000.1}'
```

Oh lastly, I don't see what exponent notation has to do with any of this.

**Comment by maxidor** [comment]
> and explain the rationale why for bonus points

I think we would all deeply benefit from actually telling us why since you opened up this issue? Everyone is fighting about it, but the OP doesn't say why. I don't see any reason why they should be banned personally.

So @turt2live: why?
