### ISSUE TITLE
Room upgrades do not state which state events should be migrated

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1843]
The [current spec states](https://matrix.org/docs/spec/client_server/unstable.html#post-matrix-client-r0-rooms-roomid-upgrade) "migrating as much data as possible over to the new room" which is rubbish and doesn't explain if non-state events should be migrated at all (Synapse does not). It also doesn't explain whether all state should be migrated or just a subset (Synapse whitelists some state)

Furthermore, https://matrix.org/docs/spec/client_server/unstable.html#post-matrix-client-r0-rooms-roomid-upgrade references it's parent module for more details which is a bit weird.

**EDIT**: 

I found some information below, but it was linked incorrectly by the above.

>Replicates the power levels, privacy, topic, and other transferable state events to the new room. This generally excludes membership events but may include client-specified events and other presentation details.

At minimum we should be stating these as their types rather than the human readable names. "other transferable state events" is still too vague and needs expanding on what makes them transferable, or a blacklist of nontransferable events.

**Comment by turt2live** [comment]
err, non-state events aren't intended to be transferred at all.

**Comment by richvdh** [comment]
it was deliberately left as an implementation-specific "do the best you can here" thing

**Comment by non-Jedi** [comment]
Further with regard to the last paragraph of the module (https://github.com/matrix-org/matrix-doc/blob/1f05c44a0bcdedb36b1c7cf28a5ca03bba199464/specification/modules/room_upgrades.rst):

> When a user joins the new room, the server may wish to automatically transfer/replicate some of the user's personalized settings such as notifications, tags, etc.

That doesn't read like a specification but a proposal. For one thing, "the server" should say "the user's server" to clarify the responsibility. Secondly, if this is a "MAY" thing, it should simply say "May" rather than "may wish to". It's better both stylistically and for clarity of someone implementing a client or server.

And third, with regard to this paragraph as well as the state-event migration verbiage brought up by Half-Shot, why is this something we wish to leave implementation-specific? Shouldn't we want clients to be able to rely on consistent behavior between homeservers for room-version upgrades? Apologies if this was discussed in the proposal somewhere already.
