### ISSUE TITLE
Register /.well-known/matrix with IANA

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1914]

**Comment by jryans** [comment]
I have submitted the registration request to the IETF group that reviews them.

**Comment by jryans** [comment]
The request has been received by IETF mailing list, and now we wait for it to be reviewed, which may take some time.

**Comment by Vikingat-RAGE** [comment]
This needs to be addressed within the specification as well. The "/.well-known/matrix/client" to my understanding does not conform to RFC 3986. The /.well-known/ must be `segment-nz` as specified in RFC 7785. Is the application name just going to be "matrix" then?

**Comment by uhoreg** [comment]
(I'm assuming you mean 5785 ratherthan 7785)  The registered name would just be `matrix`, and would be a directory.  This is similar to some other registered `.well-known` names that are also defined to be directories, such as `acme-challenge` or `dnt`

**Comment by Vikingat-RAGE** [comment]
Yes sorry that was a typo.

**Comment by jryans** [comment]
Yes, we registered for the name `matrix`.

**Comment by richvdh** [comment]
See https://mailarchive.ietf.org/arch/msg/wellknown-uri-review/4x0kkZtC8L-oztGKXGeCOUID0fk for the IETF request.

**Comment by jryans** [comment]
The `.well-known` registry request [has been reviewed](https://mailarchive.ietf.org/arch/msg/wellknown-uri-review/i3szEtSjiiCyILolka-LReNmQeE) and broadly looks good, but they are suggesting that we provide a more stable / unchanging URL to the specification documents that explain our `.well-known` behaviour so that we don't need to update the document URLs in the future.

I had previously offered:

https://matrix.org/docs/spec/client_server/r0.4.0.html#well-known-uri
https://matrix.org/docs/spec/server_server/r0.1.1.html#get-well-known-matrix-server

We could instead provide:

https://matrix.org/docs/spec/client_server/unstable.html#well-known-uri
https://matrix.org/docs/spec/server_server/unstable.html#get-well-known-matrix-server

I am not quite sure how they may feel about the word "unstable" in the URL, though I can try to explain it's just the latest reviewed version.

@ara4n @richvdh @uhoreg Since you've interacted with this issue, are there other URLs you would recommend instead? I suppose it would be possible to craft a separate page that just describes `.well-known` at an unchanging URL, but I wasn't sure if that would be desirable.

Anyway, if I don't hear any replies here soon, I'll offer the unstable URLs above.

**Comment by jcgruenhage** [comment]
It would be nice to have a "stable" pointer just like we have "unstable", where stable shows the most recent stable release. Would be really useful here, and I'm sure there's other use cases too

**Comment by richvdh** [comment]
the word you are after is "latest":

https://matrix.org/docs/spec/client_server/latest.html#well-known-uri
https://matrix.org/docs/spec/server_server/latest.html#get-well-known-matrix-server

**Comment by jryans** [comment]
Aha, thanks all! I will offer the URLs that use latest then.

**Comment by jryans** [comment]
I have [replied](https://mailarchive.ietf.org/arch/msg/wellknown-uri-review/wMPmgoLhF65AgEPqVo8Qv-OMlZk) with updated spec URLs that use "latest".

**Comment by jryans** [comment]
I registry experts have [approved our request and instructed IANA to add our registration](https://mailarchive.ietf.org/arch/msg/wellknown-uri-review/TWTcV1YvbnPG6SJV5NQqhnW5z2c). I'll update this thread once the registration goes live.

**Comment by jryans** [comment]
IANA [has added](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) the registration, so we're all done here. 🎉
