### ISSUE TITLE
Links in E2EE chats are leaked plaintext by URL preview API.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [matrix-org/matrix-doc#2120]
An example request a client (Riot) makes to the server (synapse) when receiving a link in an E2EE chat:
`GET /_matrix/media/r0/preview_url?url=https://google.com`

**Comment by t3chguy** [comment]
That's why clients like riot-web disable URL Previews by default for E2EE rooms (https://github.com/vector-im/riot-web/issues/2084)

A solution to this is possible, client can generate their own url previews, at the cost of their privacy from the target server mentioned in the url: https://github.com/vector-im/riot-web/issues/2953

**Comment by turt2live** [comment]
In practice I believe the spec just needs to recommend that clients not URL preview things in encrypted rooms, or that they do their own previews. Ultimately it's not a spec problem that the clients decide to leak this information, but the spec can recommend them to not do that.
