### ISSUE TITLE
`notifications` keys in m.room.power_levels events can be set to above the sender's power level

### ISSUE THREAD

**Issue by lucavb** [matrix-org/matrix-doc#2198]
The most recent version of the authorisation rules are the rules presented in room version 1 (and some additions in room version 3, which do not apply to the issue here). After the finalisation of room version 1 the key `notifications` was added to the `m.room.power_levels` event to determine what users are able to trigger notifications, with the most prominent example being `@room`. Since the authorisation rules are older, they do not cover this field, which leads to the fact, that currently spec conform behaviour is to let pretty much anything fly within this key.

I've asked this question before in the matrix-spec room and apparently this is not a specific decision, but instead hasn't been discussed yet. This is what this issue is for.

To me personally it seems inconsistent to not regulate this key the same way, for instance, `users` or `events` are.

[m.room.power_levels](https://matrix.org/docs/spec/client_server/r0.5.0#m-room-power-levels)
[room version 1](https://matrix.org/docs/spec/rooms/v1)

**Comment by turt2live** [comment]
The authorization rules do not control notifications, which is why it is not included. The push rule for the `@room` notification is described here: https://matrix.org/docs/spec/client_server/r0.5.0#m-rule-roomnotif

There's a condition on the push rule which requires that the permission be met. The DAG doesn't care if the user has permission to notify, so it is not covered by the push rules.

For abundance of safety: issues like this are best discussed as security issues first. Bugs in implementations or the protocol where anyone could notify the whole room (or worse) are considered security issues. More information on the security stuff can be found here: https://matrix.org/security-disclosure-policy/

**Comment by turt2live** [comment]
@lucavb has further clarified out of band what's going on here, and it indeed looks like something we should fix. Basically the current auth rules prevent Alice (PL 50) from editing anything in the power levels above their power level (ie: if `events_default` is at 75, Alice can't do anything about it despite being able to modify power levels in this scenario). The notifications section is inconsistent with this because it was introduced after the auth rules were written, so Alice can modify the notifications to be 200 then back down to 0 or whatever they like. We should probably make it consistent.
