### ISSUE TITLE
MSISDN adding APIs should clarify whether country code is required

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix-doc#2222]
MSISDN adding APIs in the CS and IS APIs suggest that the country code must be supplied, but at the moment, Sydent appears to also accept no country code, as long as the number is in E.164 format (_with_ leading + sign).

We should decide what's really intended here and update the spec and/or Sydent.

**Comment by turt2live** [comment]
As far as I can tell, it's an accident that Sydent accepts E.164 format, and the introduction of the spec somewhat confirms this. The API was originally included in https://github.com/matrix-org/matrix-doc/pull/1507 with the Sydent commit that adds the country handling as https://github.com/matrix-org/sydent/commit/c99031afc229c37675def3473b4772771ade07e6 (a couple year difference, in favour of Sydent). However, the commit in Sydent doesn't exactly inspire confidence that it's supposed to take E.164 format, and neither does the commit prior: https://github.com/matrix-org/sydent/pull/31/commits/f348aa5d32ed3a0e252b45072825a5aed3a724dd

On top of all that, supporting an optional `country` brings into question why we would have it in the first place, as we could just have E.164 formats instead. The short answer being some numbers are actually associated with multiple countries (`+1` for instance is US/Canada/other places), which makes the user experience regarding where a phone number came from a bit fiddly. It'd be awkward if the user said they're from the US then got told their phone number lives in Jamaica (because of the North American Numbering Plan). 

All told, I think Sydent is wrong here.
