### ISSUE TITLE
Unspecified whether initial_device_display_name is required in /client/r0/login

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2522]
CS spec only states that it is ignored when a `device_id` is specified *and* it is known; but not whether it is required to specify otherwise, or can be left out for eg. an auto-generated or default device display name.

Edit: To clarify, the somewhat inconsistent use of "required" and "optional" terminology in the remainder of the spec, is why I'm not sure what to interpret it as when it isn't specified.

**Comment by turt2live** [comment]
It's optional because it's not required.

We have three ways of communicating optionability (which is now a word):
* Listed as required = required.
* Not listed as required = optional.
* Listed as optional = required in some circumstance ("Optional if X is supplied")

We are consistent in this messaging as far as I'm aware. Where the confusion likely arises is when we fail to list things as required when they are required because of historical factors. We're mostly at a point where we shouldn't have this though - and where we do please do report the issues or PR fixes. 

In general, it's best to not let our historical failures affect the understanding of the spec as we're unlikely to clarify something like this.
