### ISSUE TITLE
spec is missing documentation of /_matrix/federation/v2/send_{join,leave}

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2541]
This is due to a legacy bug in Synapse from before the federation spec was a thing. It's correctly specified in the spec, but we need a /v2 endpoint of some things to remove the thing - similar to the invite endpoint.

This issue primarily exists as a place to point people who notice the weirdness.

**Comment by aaronraimist** [comment]
Wasn't that https://github.com/matrix-org/matrix-doc/issues/1418?

**Comment by turt2live** [comment]
indeed, I knew I wasn't crazy in thinking this was fixed. Looks like it needs a spec PR - I'll keep this open as a personal reminder to write that spec before we cut a release (as clearly it being a merged PR with a label isn't good enough).

**Comment by richvdh** [comment]
> as clearly it being a merged PR with a label isn't good enough

if that's true, isn't it also true of other MSCs under [spec-pr-missing](https://github.com/matrix-org/matrix-doc/issues?q=label%3Aspec-pr-missing) ?

**Comment by iinuwa** [comment]
I think I'm a little confused on this issue. So this is a spec bug and not actually implemented in Synapse/Construct? So I should use just `res` instead of `[200, res]` as the response body in the `v1` endpoint for our server library?

**Comment by richvdh** [comment]
the v1 endpoints return `[200, res]`. There also exist v2 versions of these endpoints which just return `res`: `v2/invite` has existed since s2s spec r0.1.0, and MSC1802 proposes the introduction of `v2/send_join` and `v2/send_leave`, though these have not yet made it into a released spec (though this is now just a formality).

Recent versions of synapse implement all three v2 endpoints, as well as the v1 versions for compatibility with older implementations. For outbound requests, Synapse will first try the v2 endpoints and then fall back to the v1 versions for compatibility with older servers.

I can't speak to what construct does here.

To be spec-compliant, you should follow Synapse's behaviour.

If this sounds like a mess: yes, fixing bugs in federated protocols is hard and takes ages :/.

**Comment by turt2live** [comment]
> > as clearly it being a merged PR with a label isn't good enough
> 
> if that's true, isn't it also true of other MSCs under [spec-pr-missing](https://github.com/matrix-org/matrix-doc/issues?q=label%3Aspec-pr-missing) ?

Almost certainly. Usually I try to keep an eye on that label but this particular MSC missed the queue somehow.

**Comment by iinuwa** [comment]
Does the same thing apply for the [send transaction endpoint](https://matrix.org/docs/spec/server_server/r0.1.3#put-matrix-federation-v1-send-txnid)?

**Comment by turt2live** [comment]
That would be https://github.com/matrix-org/matrix-doc/issues/2236

**Comment by iinuwa** [comment]
Ah, thank you. I didn't find it in the other events listed in the MSCs linked here, but a simple search probably would have worked. Sorry about that.
