### ISSUE TITLE
Spec does not specify whether room tag options are permitted to have custom attributes

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2714]
In the [Room Tagging](https://matrix.org/docs/spec/client_server/r0.6.1#room-tagging) section of the spec, it is *hinted at* that the options object for a tag may contain arbitrary custom attributes and it's not just limited to `order` (emphasis mine):

> The JSON object associated with each tag gives information about the tag, __e.g__ how to order the rooms with a given tag.

... but the schema for `Tag` gives no indication that such custom attributes are permitted, and implies that only spec-defined attributes may exist.

It should be made explicit whether custom attributes are permitted or not, and if so, under what restrictions; to avoid a situation like with the tags themselves, where both unprefixed and `u.`-prefixed user tags may exist.

**Comment by turt2live** [comment]
Tags are events, which means they're under the same rules governing namespacing and arbitrary data for any other event.

**Comment by joepie91** [comment]
This seems like an incomplete solution. Tag events already deviate from other events in that they have more precise / incompatible namespacing rules (specifically the `u.*` and unnamespaced tag names), so clearly the *entirety* of the event is not covered by the usual rules. That means that IMO it should clearly indicate where the normal rules start applying again.

Additionally, there don't seem to be any such general rules specified in the CS spec anyway; while it mentions namespaces for event types specifically and a few other things (algorithms, auth methods, ...), it does not do so for arbitrary attributes. The appendices also do not contain any such rules that I can find.

Likewise, I've not run into any part of the CS spec that explicitly denotes where/whether arbitrary attributes are permitted, though I've not read it back-to-front.

**Comment by KitsuneRal** [comment]
Tag names with no namespace are actually a legacy and newer code should not produce them - the section you mentioned is quite clear about that. I'm not sure what kind of incompatibility you mean - namespacing within the event content can be specific to event type, and we strive to maintain consistency on the level of `m.` and reverse-DNS names. Tag events have the `u.` namespace on top of that because that's one of rare places where key names are driven by end user input.

Technically, the APIs are open-ended when it comes to additional event attributes: unless specified otherwise, extra attributes are _usually_ permitted. Allowing additional attributes is a default in OpenAPI 2 (but not 3); however, I'd rather consider it a spec omission than a deliberate default. I agree it would be great to have a clear statement about that (I couldn't find one, either).
