### ISSUE TITLE
Add syntax highlighting to code blocks on appendices 

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2893]
https://adoring-einstein-5ea514.netlify.app/appendices/

**Comment by wbamberg** [comment]
I assume this should apply to everything, not just appendices?

**Comment by turt2live** [comment]
probably, I just happened to notice it in the appendices

**Comment by wbamberg** [comment]
This should be fixed by:

https://github.com/wbamberg/matrix-hugo/commit/5b8b712699abcbaf4d9fbb55cebb2b813edd9825
https://github.com/wbamberg/matrix-hugo/commit/50bc61be43d0ae65069abbfe26288f933ba50184
https://github.com/wbamberg/matrix-hugo/commit/e7d23fd934cd86dbc518cf8310027af915a2de94
https://github.com/wbamberg/matrix-hugo/commit/bd399b8dac94b25e6dd033ea3c1d34beaf0a5bfd
