### ISSUE TITLE
Clicking on 9 Rooms link in the new spec's TOC doesn't do anything

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix-doc#2900]
The URL changes to https://adoring-einstein-5ea514.netlify.app/client-server/#rooms but the page doesn't scroll there

**Comment by wbamberg** [comment]
Thank you for filing! I had found this problem before but forgot about it. It's because the thing that makes sure heading IDs are unique wasn't looking at the sidebar nav, and that has an element with a "rooms" ID (because there is a page called /rooms).

Should be fixed now: https://github.com/wbamberg/matrix-hugo/commit/dd325b6c269c19e53c8a5b6b3e1b80307f4d61db.

**Comment by aaronraimist** [comment]
Thanks
