### ISSUE TITLE
Request body example for /_matrix/identity/v2/account/register is just 'null'

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2932]

**Comment by wbamberg** [comment]
The data for the request body in POST /_matrix/identity/v2/account/register does not include an example. The template shouldn't render `null` in this case, it should probably omit the whole "Request body example" bit.

The current template code tries to generate an example from the schema, if no explicit example is included: https://github.com/matrix-org/matrix-doc/blob/7aded5be4dadc36bafdeeb16193d3b94a6c7e48d/scripts/templating/matrix_templates/units.py#L444-L450

I think this is not a good idea, and we should not do the same in the new system. Examples should be written by humans, who are better able to ensure that they are correct and useful. The generated example for POST /_matrix/identity/v2/account/register (https://matrix.org/docs/spec/identity_service/r0.3.0#post-matrix-identity-v2-account-register) is a case in point, as it seems to be nonsensical.

So I think the fix for this in the templating code should be just to omit the "Request body example" part of the output if an explicit example wasn't found.

**Comment by turt2live** [comment]
can we make it spit out an error block instead of hiding the problem? A giant ugly red box saying that you're missing an example is a lot clearer than nothing :)

**Comment by wbamberg** [comment]
> can we make it spit out an error block instead of hiding the problem? A giant ugly red box saying that you're missing an example is a lot clearer than nothing :)

Well, sort of. We can easily determine whether there's any example at all. It's harder but possible to determine whether an example contains all mandatory pieces. It's basically impossible to determine whether an example fulfills any extra requirements (like, "the string must be 'Bearer' ", or "either of `property1` or `property2` must be present but not both").

But that aside, I don't think we should handle errors in the data by plastering ugly boxes on the site. We should aim to make the site as usable as possible for readers, and this kind of thing would make it worse (by analogy, do we handle bugs in Element by flagging them in the UI like this?). If it's so important to have examples for all the data, we should make the Hugo build fail if examples are missing. If it isn't important enough for that, we should just file an issue to add them and ignore missing examples in the site.

**Comment by turt2live** [comment]
we can probably treat schema validation ("must be Bearer") and example presence as something different - the first fails at build time whereas the other is just ugly boxes. In this particular issue's case, it seems like there is no example (given `null`), so I would expect a red box for it if I were to make the mistake during development.

Element handles bugs a bit differently - it tries to recover as best as it can visually when there's a problem, but there are certain areas where it intentionally causes undesirable behaviour to encourage a bug report or support request. An example of this is the room list on element-web intentionally falling into a failure mode where it starts to duplicate rooms when something goes wrong in hopes that someone reports it, whereas something like encryption not working tries to gracefully fail by just not exposing that UI to the user (in theory).

**Comment by wbamberg** [comment]
OK, I still don't think "show an warning box to readers" is the right way to handle this, but I've implemented it: https://adoring-einstein-5ea514.netlify.app/identity_service_api/#post_matrixidentityv2accountregister

**Comment by turt2live** [comment]
hmm, the goal here is to make sure we fill out the examples but make it easily identifiable when we forget to make them. An error to the effect of "Specification error: Example invalid or not present" would communicate to authors that they missed a step and give a hint to readers that something is just missing if we somehow overlook it.

**Comment by wbamberg** [comment]
OK, I've updated the message :).

**Comment by wbamberg** [comment]
@turt2live , can we close this?
-> https://adoring-einstein-5ea514.netlify.app/identity-service-api/#post_matrixidentityv2accountregister

**Comment by turt2live** [comment]
looks great, thanks!
