### ISSUE TITLE
cross-signing: incorrect and inaccurate documentation

### ISSUE THREAD

**Issue by nikolockenvitz** [matrix-org/matrix-doc#2950]
Hi, I was reading through the specs and found some parts that I think are not correct or are at least missing a bit more clarification. I also have some questions I found no answer for in the specs/issues.

Most of it is related to cross-signing and self-/user-signing keys (introduced in f4fe318a85f4cefe00ca15e49914ea2b7b061bea).

---

https://github.com/matrix-org/matrix-doc/blob/7aded5be4dadc36bafdeeb16193d3b94a6c7e48d/proposals/1756-cross-signing.md#L531-L532

They sign the master key and not each others self-signing key, right? (btw, are there any plans to rename that to e.g. "primary key"?)

---

https://github.com/matrix-org/matrix-doc/blob/7aded5be4dadc36bafdeeb16193d3b94a6c7e48d/proposals/1756-cross-signing.md#L545-L546

This statement is confusing me a bit. Intuitively I would have assumed that only the self-signing key needs to be re-issued (master key revokes previous self-signing key, master key signs new self-signing key, new self-signing key signs all valid devices).
Just re-issuing the user-signing key would not break the trust.

> Alice's device will trust Bob's device if:
>
> * Alice's device is using a master key that has signed her user-signing key,
> * Alice's user-signing key has signed Bob's master key,
> * Bob's master key has signed Bob's self-signing key, and
> * Bob's self-signing key has signed Bob's device key.

Let's say one of Bob's devices is stolen. That device is still signed by the self-signing key of Bob. The self-signing key is still signed by Bob's master key. Bob's master key is still signed by Alice's user-signing key and that user-signing key is still signed by Alice's master key.

But even when changing the line to `then only the self-signing key must be re-issued` I am still missing a bit more details about the assumptions you made. In that case it is assumed that the stolen device doesn't disclose the master and the user-signing key to the attacker, right? Then, these keys would need to be rotated too, right? You may wanna put that assumption into the text so that it's clear which keys need to be re-issued depending on which keys are disclosed.
Wouldn't it also be possible that the signature of the stolen device's key (by the self-signing key) is revoked (assuming that only the device key is disclosed but not the master/self-/user-signing key)?

---

Just a further question related to that topic: Which key rotations require re-verifying other users? Is it only when the master key is re-issued or also when the user-signing key is re-issued? Would you mind elaborating a little bit more on that?

https://github.com/matrix-org/matrix-doc/blob/7aded5be4dadc36bafdeeb16193d3b94a6c7e48d/specification/modules/end_to_end_encryption.rst#L898-L900

---

Thanks in advance and best regards,
Niko

**Comment by uhoreg** [comment]
FYI, cross-signing is now in the unstable spec (https://matrix.org/docs/spec/client_server/unstable#cross-signing), so that should be used as the canonical reference.

For your first two questions, yes, those spots need fixing.  They may have been correct for a previous version, and never updated.  I've opened to fix those issues.  Can you check that those changes address your concerns?

For your third question, if you issue a new master key, then you will probably also be issuing new user-signing and self-signing keys.  The master key is generally treated more securely than the others, so if it is compromised, then it's likely that the others are too.  If you issue a new master key, then anyone who signed your previous master key will need to re-verify.

If you issue a new user-signing or self-signing key, then you may or may not need to verify, depending on whether you believe the old key has already been used to issue signatures for bad keys, or if you're reissuing the keys for preventative reasons (or if you have a set of known-good signatures).  If you know that the signatures are all still good, you could re-sign the keys without re-verifying.  But if not, you would want to re-verify.  (I don't know of any clients that will re-sign devices based on the old signatures.)

**Comment by nikolockenvitz** [comment]
Thank you very much for the very fast, comprehensive and helpful response!! Yes, changes look good. Again, thanks for your help!
