### ISSUE TITLE
Add `needs-implementation` label

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix-doc#3159]
Add `needs-implementation` label so it's easier to tell if a MSC has been validated or why it's stuck.

Seems like it would also be nice to also sort by `has-implementation` so a scoped label might be more appropriate.

 - `implementation:needed`
 - `implementation:complete` (better word? `available`, `up-to-date`, `ready`)
 
 ---
 
 Spawned from question asked in [@ara4n's *Demystifying MSCs* talk](https://youtu.be/SFkZz60RRfc?t=3647).
 
 I'm curious on the percentage of MSC's still drafting vs awaiting an implementation.

**Comment by turt2live** [comment]
My biggest concern is the administrative effort required to maintain that label: the SCT would want to validate that an implementation matches the MSC, and is suitable for being counted as a complete enough implementation. This effectively creates 3 states: none, submitted, and validated. (though we should use different words because these have somewhat net-negative connotations) 

To avoid administrative effort, and to avoid spammy implementations being recorded, the bot could post to #sct-office that an implementation has been submitted so someone from the SCT can update the labels.

**Comment by turt2live** [comment]
... though the amount of administrative effort with that bot approach is still questionable. I wonder how much we can trust the tooling to not be abused...

**Comment by MadLittleMods** [comment]
> To avoid administrative effort, and to avoid spammy implementations being recorded, the bot could post to #sct-office that an implementation has been submitted so someone from the SCT can update the labels.


How does this look:

 - `@mscbot implementation submit https://github.com/matrix-org/synapse/pull/9247` -> message in `#sct-office:matrix.org` (from any community member)
 - `@mscbot implementation approve` (from SCT members) -> Adds `implementation:complete` label

`@mscbot` docs for reference: https://github.com/matrix-org/mscbot-python/blob/master/docs/user_guide.md

We can add submit command to a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for people to reference when they get to that point. Or the bot can add a comment about it.

**Comment by turt2live** [comment]
I'd probably skip the approve command only because the SCT already has access to the labels directly. What would be interesting is if the bot was made stateful (or possibly just write a new bot which happens to use the same account) so we can ✅ react to the Matrix message.

**Comment by turt2live** [comment]
as for the PR template: it's basically useless to touch that thing. It's not exposed anywhere in the github UI, and we've had one for years.

**Comment by ShadowJonathan** [comment]
What's also interesting is; what would be a "critical mass" that is enough consider a MSC "impl-tested"?

That's probably going to be decided on a case-by-case basis, but having a rule of thumb could help a bit with deciding such things.

**Comment by turt2live** [comment]
That is documented on the proposal guidelines. Let's keep this about the labels please...

**Comment by turt2live** [comment]
added, due to it being useful for more than random implementors. It can also be useful for us to see what kind of review is pending.

Implementation details:
https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$kKRgUWDKCR8O5qWVlxuFwDSXR3RWuZNZRzD214HPzPg?via=matrix.org&via=vector.modular.im&via=kde.org

**Comment by MadLittleMods** [comment]
:tada: 211/229 need implementations. Would be cool to add this distinction to the [Matrix spec graph in TWIM](https://matrix.org/blog/2021/06/04/this-week-in-matrix-2021-06-04#spec) each week.

 - https://github.com/matrix-org/matrix-doc/pulls?q=is%3Aopen+is%3Apr+label%3Aproposal+label%3Aneeds-implementation
 - https://github.com/matrix-org/matrix-doc/pulls?q=is%3Aopen+is%3Apr+label%3Aproposal
 
 Thanks @turt2live!
