### ISSUE TITLE
Delete all files uploaded by specifi user

### ISSUE THREAD

**Issue by githuberyt** [matrix-org/matrix-doc#3256]
there should be an option to delete all media uploaded by specific user or deleting a user should delete the uploaded files on the server 

spammers are taking advantage of this issue through using flooding bots to upload bulk data on the server and flood it there should be an options to ban this behavior

**Comment by richvdh** [comment]
this seems like it would be an implementation-specific feature, rather than something appropriate to the Matrix protocol as a whole?

For Synapse, I don't think there is a way to do this directly, but you should be able to script something by combining the ["list media of a user" api](https://matrix-org.github.io/synapse/develop/admin_api/user_admin_api.html#list-media-of-a-user) with the ["delete media" api](https://matrix-org.github.io/synapse/develop/admin_api/media_admin_api.html#delete-a-specific-local-media).
