### ISSUE TITLE
spec does not specify if `base_url` in client `well-known` should include trailing slash

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#3465]
**Link to problem area**:

https://spec.matrix.org/unstable/client-server-api/#well-known-uri

**Issue**

The spec just says: "This value is to be used as the base URL of the homeserver.", without giving further details.

This means that different implementations will do different things and have different expectations, leading to incompatibility - see https://gitlab.com/HengYeDev/harbour-sailtrix/-/issues/35 for example.

**Comment by richvdh** [comment]
worth noting that synapse currently returns a `.well-known` response *with* a trailing slash (eg, in the `/login` response), but https://matrix.org/.well-known/matrix/client lacks one.

**Comment by turt2live** [comment]
Related https://github.com/matrix-org/matrix-doc/issues/2780

**Comment by callahad** [comment]
Rather than the spec recommending one approach or another, perhaps it should explicitly instruct developers to handle both cases and leave it at that?

To wit: If the Spec came down on either side, it would still be trivial for severs, admins, etc. to accidentally do it the other way. The existing Matrixverse _already_ has significant inconsistency (matrix.org serves a `well-known` file which omits the `/`, but otherwise Synapse _adds_ a `/` by default). We're not going to wrench this into alignment, so probably best to chalk it up to [Postel's Law ](https://en.wikipedia.org/wiki/Robustness_principle). Synapse should be more consistent, but other software should be prepared for both scenarios.

**Comment by KitsuneRal** [comment]
Naively gluing relative URL of the endpoint to the base URL is prone to other issues too; so I tend to agree that documenting the potential pitfall is the best way forward. Quotient learned to always do the right thing some 2 years ago, FWIW; Qt, notably, has API for that which the Sailtrix guy unfortunately didn't use even in the fix.

**Comment by richvdh** [comment]
yes, at this point I fear we'll have to warn clients to accept both.

(but since you mention Postel's Law, I'll highlight the "criticism" section of that wiki page, which basically says relying on Postel's law is a terrible idea for new protocols. It's a shame we didn't sort this out sooner.)
