### ISSUE TITLE
Add a Way to (un)Mute, for a fixed period.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-doc#817]
Just as bans on IRC, and even "/shun"s can be issued for a fixed time period, so can muting a MXID, like IRC devoice "-v".  

For Moderation purposes, this can be issued for a time period.

It could also be used with IRC style anti-flood protection, with a wildcard mask, or another mechanism.  

On join, all could be muted, and perhaps a round-robin, mechanism allowing them to send, during a window, could be implemented, separately.

But, for Moderation, a user might be given a m.notice, for example, that they have been muted, for a specified period of time.

**Comment by Half-Shot** [comment]
I'll answer #814 in here too because they appear to be similar questions.

Timed operations on Matrix isn't common because it can cause all sorts of problems if servers go down or miss messages. There are ways to account for this, but it's a bit tedious which leads me onto my next point. I don't really see the point of the feature. 

Muting/Banning isn't something I'd consider a 'timed' operation. It is something I'd consider to be something to be taken carefully when no other option is available and in these cases, a human approach is better to unban/mute at a moderators discretion. I think the work involved in making this reliable for federation isn't going to be worth it for the need. I'd suggest a moderation bot as an approach for this.

>But, for Moderation, a user might be given a m.notice, for example, that they have been muted, for a specified period of time.

Power level changes arguably *should* be displayed to the user, or possibly the room at large.

**Comment by MilkManzJourDaddy** [comment]
In function the effect is the same, and exact timing is not critical, but just referenced from the HS of the Admin'/Mod'/Custom_PL which issued the event.  

What we have when we go away from the "Kitchen Sink" model of including within the spec' is the old fragmented IRC model, or the neutrality of the XEF, where, instead, "Historical XEPs" get written about what various groups decide to implement.

With Matrix, guardians of the spec' decide what is entailed, and what functionality compliant clients must have.  A problem with progresss of IRC is that clients would not be compatible with upgrades, and there are many different IRC Servers, typically called IRCds.  But, Matrix is a new thing, and there is no need to strip away the core functionality, and give it to arbitrary 'bots.
