### ISSUE TITLE
Add to the "Kitchen Sink" of the Matrix Spec', the ability to "Whisper" in group chat rooms.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-doc#822]
This seems to be in debate at the current time, in [#matrix:matrix.org](https://riot.im/app/#/room/!cURbafjkfsMDVwdRDQ:matrix.org) .  

XMPP even has this.  

[@matthew:matrix.org](https://riot.im/app/#/user/@matthew:matrix.org) a.k.a. [@ara4n](https://github.com/ara4n) mentioned that "[whispering should be through per-msg ACLs when we get there.](https://riot.im/app/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/%241488398507188570sFZPK:matrix.org
)"

> Usage note; "Kitchen Sink": 
>People often suggest features be handled by (ro)bots, instead of integral to the "Kitchen Sink".  As others have pointed out, this might not be the best approach.
>>[XMPP also has a fragmented ecosystem where the chances that your client and your server supports the same stuff as their client and their server is rather low ^^](https://riot.im/app/#/room/#matrix:matrix.org/$14883975691bgMld:gruenhage.xyz)  
>
>Matrix is often compared to XMPP, and IRC, services with**out** a "Kitchen Sink" approach.  It is done in the FAQ, for [IRC here](http://matrix.org/docs/guides/faq.html#what-is-the-difference-between-matrix-and-irc), and [XMPP here](http://matrix.org/docs/guides/faq.html#what-is-the-difference-between-matrix-and-xmpp).
>
>The FAQ states: "[Matrix has a deliberately extensive 'kitchen sink' baseline of functionality; XMPP has a deliberately minimal baseline set of functionality.](http://matrix.org/docs/guides/faq.html#what-is-the-difference-between-matrix-and-xmpp)"
>
>[@matthew:matrix.org](https://riot.im/app/#/user/@matthew:matrix.org) a.k.a. [@ara4n](https://github.com/ara4n) Wrote:
>>['kitchen sink' is an idiom in english meaning 'everything included, and then some'](https://riot.im/app/#/room/#matrix:matrix.org/$1488398387187529yVyUT:matrix.org)
>
>>[i.e. you get everything you need, even including stuff you'd expect to be there already, e.g. a kitchen sink](https://riot.im/app/#/room/#matrix:matrix.org/$1488398435187920VKveX:matrix.org)
>
>>["the whole enchilada" would be a US equivalent.](https://riot.im/app/#/room/#matrix:matrix.org/$1488398450188044oyhIt:matrix.org)

**Comment by Mikaela** [comment]
These are my concerns with whispering and what has happened at XMPP and I hope they will be considered in potential specification in order to make Matrix not become less secure considering harassment. 

> * Mikaela hopes whispers won't come or if they do, with clear method for blocking them

> people do whisper thing like "what a beautiful woman we have here"...

> either do it in public so mods can handle it or give me the ability to prevent receiving the message so it's not word of one person versus word of another person

**Comment by thekyriarchy** [comment]
I proposed this in [the aforementioned discussion](https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1488394841155576GkEbj:matrix.org) because it can be useful to send a quick/offtopic message to a subset of users in a channel about something small or only affecting them, especially in high-traffic rooms, without necessarily starting a new discussion. That means it should discourage being easy to have entire whispered/secret conversations in a channel, but still be much easier than creating a new room and inviting users to it (possibly to facilitate the decision of whether a discussion is worth continuing in a new room). 

I see two possibilities which came out of the discussion: 
* Best is probably to make the entire whisper visible to everyone, but hidden by default. 
* Less ideal is using e2e encryption so that the event is visible but contents are not.

**Comment by MilkManzJourDaddy** [comment]
When people send messages that are against the [Code of Conduct | Matrix.org](https://matrix.org/docs/guides/code_of_conduct.html), and which is "harmful to the community", or members thereof, it is probably better that they do so privately.  And, with the present state of Matrix; no Moderator who is not also in some encrypted, invite-only room, not in the directory, will be able to do anything about that.  So, it's actually better if it's kept off the communities' "radar", or out of sight.

A bit of logic: Cars (Motorized Vehicles) have been used as weapons.  Should everyone who wants to own a car only be a police or military person?

[@thekyriarchy](https://github.com/thekyriarchy) makes good use-case points.  The **ab**use happens despite the technology.  And in this case, it is better if offensive things are kept out of public rooms.  Regardless, it is a great tool.  Focus on the positive.

**Comment by thekyriarchy** [comment]
I actually disagree with that logic entirely. That logic basically says that harassment and abuse should be swept back under the rug so that only those likely to be harassed will have to deal with them or leave, which ToS, CoC, or other community standards docs exist in part to protect but would now be out of purview. 

I should hope a solution where this does not enable harassment to go out of sight at all. If anything, possibly providing a false sense of security for harassers to be weeded out by moderators, but hopefully not that either.

**Comment by MilkManzJourDaddy** [comment]
Well, the logic is being used against your suggestion.  

Really, it seems like a separate issue, "best practices"/Code of Conduct, et cetera, aside from the usefulness of a feature.  

Yes, invite-only rooms can be used to spread messages that are unflattering to certain users.  That doesn't mean invite-only rooms should be eradicated.  Just as cars are very useful, despite the way they can be **ab**used.  The misdeeds do not warrant the eradication of cars, as they serve a greater good.  Electric versus petroleum cars is a separate matter, entirely.  

And, it seems the co-founder of Matrix leans towards the concept, if I interpret his comment correctly. "[whispering should be through per-msg ACLs when we get there.](https://riot.im/app/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/%241488398507188570sFZPK:matrix.org
)"  It's just a matter of time, with other issues at the front of the queue.

**Comment by thekyriarchy** [comment]
Good, my suggestion **should** be vetted against that logic. 

Technology is never neutral nor separable from the context from which it emerges, the literal functions of its design, the places and ways it is implemented, and the people who use and interact with it. 

> "Software’s fringe existence seems to corroborate the commonsense notion that it is “intangible” rather than physical, that it is something more like a social convention or rule than machine-thing. The characteristics of software as a material object, as a means of production, as a human-technical hybrid, as a medium of communication, as terrain of political-economic contestation—in short as sociality—seem hard to represent. Software as a material with specificities, singularities, traits, and modes of existence has been displaced by software as mundane application, as infrastructural element in a wider social or technological change (the information revolution, “digital culture,” “new media,” “network society” or “convergence”)."

and 

>"code can be seen both as a discursive practice — in that is an expressive medium that can shape personal conceptions of the world, […] and a productive apparatus that contributes to the regulation of a biopolitical paradigm (that is, code directly affects the productive capacities of an individual via software programs)"

but academic-speak aside, its nonsensical to assert that the way something works is divorced from how its used. your "cars as weapons" analogy is so reductive and simplistic. there is nobody here who hasn't thought far past that idea. we're talking about the nuances of how different mechanisms and implementations may enable/disable encourage/discourage different types of interaction. so let's stop treating this like yes vs no argument over implementing anything that might be useful vs dangerous and discuss the many different considerations on how it might or might not be done, used, needed, etc.

**Comment by MilkManzJourDaddy** [comment]
Yeah, anyway...

FTR, I have reported the two MXIDs' content, in the few messages, starting [here](https://riot.im/app/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/$14883978042mKsFe:gruenhage.xyz).  

Others should do the same.

**Comment by MilkManzJourDaddy** [comment]
I don't have to vet that call against any "Social Justice Warrior" handbook, either.  The behavior was clearly unacceptable to any observing responsible adult in the room; even "simplistic" me.  

I would have filed a report sooner, but my knuckles were dragging on the floor, on my way to begin typing the above, in THIS content stream, which should be focused on the issue at hand.   

**Now**, the link to the first post of the offensive content referenced herein is in the [above post](https://github.com/matrix-org/matrix-doc/issues/822#issuecomment-283493722).  It is not all that difficult to use Riot-'droid, et cetera, to report content, as that is the proper outlet for such valid complaint.

I can now direct my "simplistic" attention elsewhere!

**Comment by thekyriarchy** [comment]
why would you report @Mikaela in the channel for bringing the issue up and why are you talking about that here? you'd strayed us far enough off topic before, and now you're barely intelligible.

**Comment by MilkManzJourDaddy** [comment]
You should **NOT** pick on  [@Mikaela](https://github.com/Mikaela) for having brought up that she was offended by those two.  It is not at all noble.  And just "not cool".

It is part of the discussion of this "Whisper" concept, as it happened in #matrix:matrix.org while this was brought up.  Not cool!

**Comment by MilkManzJourDaddy** [comment]
That sort of steerage towards [Ad Hominem](https://yourlogicalfallacyis.com/ad-hominem) ploys might gain more traction, but for the fact that the [above post, absolutely unedited](https://github.com/matrix-org/matrix-doc/issues/822#issuecomment-283493722) points to the offensive content with an embedded link, here:  https://riot.im/app/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/$14883978042mKsFe:gruenhage.xyz  and **both** the **H**ome**S**erver gruenhage.xyz **and** the **H**ome**S**erver kolm.io  are **NOT** the **H**ome**S**erver of the MXID [@Mikaela](https://github.com/Mikaela) used there.  What I **reported*  was the content that offender her So, for lack of a better cliché, a most disingenuous "Nice try."

**Comment by MilkManzJourDaddy** [comment]
**NOW**  Back to the topic.  Regardless, this is a reference for when a PR might happen.  But, hopefully, from here on, posts/comments will be on topic.  We can only hope.

**Comment by thekyriarchy** [comment]
>You should NOT pick on @​Mikaela

I realized, hence the quick edit. Why bring that up long after it was corrected?...why link to logical fallacies?...or restate all of that?...and bold all those words/letters?...or—you know what I'll just take the L on this

**Comment by richvdh** [comment]
This thread did not make happy reading this morning.

I am closing, and locking, this issue, and opening https://github.com/vector-im/riot-web/issues/3345 in its place, in which I have attempted to summarise the relevant points from this discussion. Although it might well require support in the matrix protocol, we find it easier to triage feature requests by driving them from the product side; hence the move to riot-web.

A few points, if I may:

* Given the huge number of feature requests and issues projects like Matrix/Riot have to deal with, triaging them is made much easier if such requests are short and to the point. Discussions about the definition of a kitchen sink are likely to get your feature ignored in favour of those that don't require us to read a wall of text with erratic formatting.
* Those following github issues by email (or matrix notifications) will see the first submission of a github comment. It is at *best* confusing to discover that a post has since been significantly edited. The edit feature should therefore be used sparingly, if at all. Instead please consider what you have to say carefully before posting.
* Please remember that what you write in github issues remains, effectively forever, as a publicly-visible statement of your own attitude. You are also, to some level, representing the project; a new user will not be encouraged to see this sort of conversation. Please also remember that we also seek to be inclusive as a project, and you may find yourself in discussion with people with different backgrounds and opinions. If you find yourself offended, you will do better to ignore or report the offence than to engage with the offender. In short: be respectful of others and seek to de-escalate conflict.
