### ISSUE TITLE
bulleted list in docs/projects/other/sydent.html does not show up correctly

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-doc#923]
interestingly, the GitHub preview for that doc renders the list as a list, but in the HTML, it isn't recognized as a list.  (Thanks to WubTheCaptain for pointing it out in https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$14954592511921492UdAHg:matrix.org)

**Comment by t3chguy** [comment]
Could it be related to the JS SE
```
Uncaught Error: Syntax error, unrecognized expression: a[href*=#]:not([href=#])
    at Function.fa.error (jquery.js:2)
    at fa.tokenize (jquery.js:2)
    at fa.select (jquery.js:2)
    at Function.fa [as find] (jquery.js:2)
    at n.fn.init.find (jquery.js:2)
    at n.fn.init (jquery.js:2)
    at n (jquery.js:2)
    at HTMLDocument.<anonymous> (custom.js:2601)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
```

**Comment by uhoreg** [comment]
patch by WebTheCaptain at https://paste.debian.net/plainh/f265f6f7

**Comment by richvdh** [comment]
@maxidor discovered this separately; the problem was indeed the missing empty line. (If you thought markdown would be interpreted consistently everywhere, [HAHAHA YOU LOSE](https://twitter.com/gruber/status/507670720886091776).)

So I've fixed the proximal problem in https://github.com/matrix-org/matrix-doc/commit/a42d3011b78911975dac8d925825ba25553d52b0, however we now have a separate problem, which is that the CSS is a complete disaster zone. But that's more of a problem with matrix.org, so I'm closing this and opening https://github.com/matrix-org/matrix.org/issues/22.
